export interface SpaceArtifact {
  id: string;
  index: string;
  title: string;
  titleZh: string;
  category: string;
  date: string;
  material: string;
  location: string;
  position: readonly [number, number, number];
  accent: string;
  image: string;
  imageAlt: string;
  sourceLabel: string;
  sourceUrl: string;
  story: string;
  interpretation: string;
  recordStatus: string;
}

const officialSource = "https://www.beijing.gov.cn/renwen/bjgk/dxgk/dxwb/202303/t20230321_2941399.html";

export const spaceArtifacts: readonly SpaceArtifact[] = [
  {
    id: "tanbo-buddhist-display",
    index: "01",
    title: "Buddhist figures on public display",
    titleZh: "佛学艺术馆公开展陈佛像组合",
    category: "BUDDHIST ART",
    date: "公开资料未著录",
    material: "公开资料未著录",
    location: "北侧展墙 · 影像画框",
    position: [-8.3, 2.8, -16.15],
    accent: "#c2a164",
    image: "/assets/curation-space/tanbo-buddhist-display.jpg",
    imageAlt: "坦博兴善苑佛学艺术馆公开照片中的两尊佛像",
    sourceLabel: "北京市人民政府 · 坦博兴善苑",
    sourceUrl: officialSource,
    story: "北京市人民政府于 2023 年发布的坦博兴善苑介绍，将这张照片置于佛学艺术馆条目之后。照片可确认两尊佛像曾作为该馆公开展陈图像出现；页面未提供单件名称、年代、材质、尺寸或馆藏编号，因此本演示不做进一步断代或命名。",
    interpretation: "示意陈列保留实拍图中的并置关系，将经核验的公开照片作为北侧展墙画框内容。当前不生成与馆藏不符的三维替代物；待馆方提供多角度影像、尺寸基准与单件著录后，再替换为可信的摄影测量模型。",
    recordStatus: "VERIFIED PUBLIC DISPLAY IMAGE · CATALOGUE PENDING",
  },
  {
    id: "tanbo-multiarm-display",
    index: "02",
    title: "Multi-armed figure on public display",
    titleZh: "佛造像艺术馆多臂造像",
    category: "SCULPTURE",
    date: "公开资料未著录",
    material: "公开资料未著录",
    location: "北侧展墙 · 影像画框",
    position: [5.6, 2.8, -16.15],
    accent: "#b79057",
    image: "/assets/curation-space/tanbo-multiarm-display.jpg",
    imageAlt: "坦博兴善苑佛造像艺术馆公开照片中的多臂造像",
    sourceLabel: "北京市人民政府 · 坦博兴善苑",
    sourceUrl: officialSource,
    story: "这张多臂造像照片来自北京市人民政府的坦博兴善苑介绍，并紧随佛造像艺术馆的说明出现。公开资料只足以确认其展陈类别与可见形态，尚不足以判断具体尊名、年代、地域和材质。",
    interpretation: "多臂轮廓适合在数字档案中以热点拆解手印与持物。现阶段只使用经核验的正面实拍作为画框内容，不再展示粗糙的三维简模；后续获得背面、侧面与尺寸基准照片后，才能制作可靠的馆藏摄影测量模型。",
    recordStatus: "VERIFIED PUBLIC DISPLAY IMAGE · CATALOGUE PENDING",
  },
  {
    id: "epsilon-1",
    index: "03",
    title: "Aṣṭasāhasrikā Prajñāpāramitā",
    titleZh: "《八千颂般若波罗蜜多经》贝叶",
    category: "PALM-LEAF MANUSCRIPT",
    date: "11 世纪",
    material: "贝叶、矿物颜料与刻划文字",
    location: "东侧展墙 · 恒湿横向展龛",
    position: [0.48, 0.56, 0],
    accent: "#c49b58",
    image: "/assets/curation/prajnaparamita-folio.webp",
    imageAlt: "绘有佛陀与胁侍的十一世纪梵文贝叶经残叶",
    sourceLabel: "Wellcome Collection",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Folio_208_recto_of_Sanskrit_palm_leaf_manuscript_Wellcome_L0015554.jpg",
    story: "这件 11 世纪贝叶经残叶出自印度东部那烂陀一带，将经文、佛像绘画与仪式阅读压缩在同一片脆弱的贝叶上。叶面仍能辨认纤维方向、刻划文字和红赭色颜料，是研究文本传播与材料老化的重要实例。",
    interpretation: "横向恒湿展龛贴靠东墙布置，观众不需要跨越水池边缘便能观看。数字档案可分别记录纤维、颜料与边缘缺损，并让研究者在不反复接触原件的情况下放大比对。",
    recordStatus: "VERIFIED RECORD · CC BY 4.0",
  },
  {
    id: "south-india-123",
    index: "04",
    title: "Pali Manuscript",
    titleZh: "南印度巴利文贝叶经册",
    category: "PALM-LEAF MANUSCRIPT",
    date: "18 世纪",
    material: "贝叶、穿绳与木质护板",
    location: "东侧展墙 · 恒湿横向展龛",
    position: [0.58, 0.56, 0],
    accent: "#b6a778",
    image: "/assets/curation/pali-manuscript-south-india.webp",
    imageAlt: "以绳穿联的南印度巴利文贝叶经册",
    sourceLabel: "The Metropolitan Museum of Art",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/38029",
    story: "这册 18 世纪南印度巴利文写本保留了贝叶、穿孔、系绳和护板共同构成的阅读系统。展开的叶片边缘呈现厚度、错位与使用磨损，使它不仅是一段文字，也是能够被数字化记录的三维装帧结构。",
    interpretation: "展龛采用低照度横向陈列，以完整呈现狭长书册与穿绳关系。后续摄影测量应补拍叶片侧面、孔位和叠层，让线上模型能够拆解装帧而不替代原件著录。",
    recordStatus: "VERIFIED RECORD · PUBLIC DOMAIN",
  },
  {
    id: "tanbo-gold-silver-display",
    index: "05",
    title: "Gold and silver objects on public display",
    titleZh: "金银器艺术馆公开展陈组合",
    category: "METALWORK",
    date: "公开资料未著录",
    material: "公开资料未著录",
    location: "南侧展墙 · 影像画框",
    position: [-5.6, 3.2, 13.5],
    accent: "#c39a58",
    image: "/assets/curation-space/tanbo-gold-silver-display.jpg",
    imageAlt: "坦博兴善苑金银器艺术馆公开照片中的展陈组合",
    sourceLabel: "北京市人民政府 · 坦博兴善苑",
    sourceUrl: officialSource,
    story: "这张公开照片出现在北京市人民政府对坦博兴善苑艺术馆群的介绍中，可用于确认金银器类别及其现场展陈氛围。页面没有给出单件名称、年代、材质成分或馆藏编号，因此当前数字档案仅记录可核验的图像事实。",
    interpretation: "南墙采用较宽的影像画框保留原照片中的成组陈列关系。正式数字化阶段应按单件拆分，补充尺度、重量、工艺痕迹与多角度高分辨率影像。",
    recordStatus: "VERIFIED PUBLIC DISPLAY IMAGE · CATALOGUE PENDING",
  },
  {
    id: "tanbo-jade-display",
    index: "06",
    title: "Jade objects on public display",
    titleZh: "玉器艺术馆公开展陈",
    category: "JADE",
    date: "公开资料未著录",
    material: "公开资料未著录",
    location: "南侧展墙 · 竖向影像画框",
    position: [5.2, 3.35, 13.5],
    accent: "#9ea68f",
    image: "/assets/curation-space/tanbo-jade-display.jpg",
    imageAlt: "坦博兴善苑玉器艺术馆公开照片中的竖向展陈",
    sourceLabel: "北京市人民政府 · 坦博兴善苑",
    sourceUrl: officialSource,
    story: "北京市人民政府的公开页面以竖幅照片呈现玉器艺术馆的部分陈列。当前资料只能确认展陈类别与可见轮廓，无法据此判断玉种、年代、产地或具体器名。",
    interpretation: "竖向画框与原始照片比例一致，使南墙形成与横幅金银器影像不同的节奏。获得馆方著录后，可进一步补充透射光、表面反射与微痕数字采集。",
    recordStatus: "VERIFIED PUBLIC DISPLAY IMAGE · CATALOGUE PENDING",
  },
  {
    id: "india-2157",
    index: "07",
    title: "Pali Manuscript with carved wooden covers",
    titleZh: "印度巴利文贝叶经木质护板",
    category: "PALM-LEAF MANUSCRIPT",
    date: "18 世纪",
    material: "贝叶与雕刻木质护板",
    location: "西侧展墙 · 横向影像画框",
    position: [-17.5, 2.75, -4.0],
    accent: "#aa8e63",
    image: "/assets/curation/pali-manuscript-india.webp",
    imageAlt: "带有雕刻木质护板的印度巴利文贝叶经",
    sourceLabel: "The Metropolitan Museum of Art",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/38030",
    story: "这件 18 世纪印度写本以雕刻木板保护狭长的贝叶文本，两处穿孔将护板与叶片组织成可以携带和阅读的整体。它说明数字化对象不仅是文字页面，也包括装帧、叠层与使用痕迹。",
    interpretation: "西墙使用狭长横框呈现护板与文本的完整比例。后续可分别采集雕刻深度、穿孔轴线和叶片侧缘，形成可拆解的三维装帧档案。",
    recordStatus: "VERIFIED RECORD · PUBLIC DOMAIN",
  },
  {
    id: "nepal-124b",
    index: "08",
    title: "Cullavagga Fragment, folio 124b",
    titleZh: "尼泊尔《小品律》贝叶残叶",
    category: "PALM-LEAF MANUSCRIPT",
    date: "9 世纪",
    material: "贝叶墨书",
    location: "西侧展墙 · 超长横向影像画框",
    position: [-17.5, 2.55, 4.2],
    accent: "#8f8265",
    image: "/assets/curation/pali-manuscript-nepal.webp",
    imageAlt: "以早期文字密集书写的尼泊尔巴利文贝叶残叶",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:A_Pali_Manuscript_in_Nepal.jpg",
    story: "这件尼泊尔残叶保存了处于过渡阶段的早期文字形态。狭长叶面上的密集行文与断裂接缝，使它适合用于文字比对、虚拟拼接和长期保存状态监测。",
    interpretation: "超长横框按原物比例强调文字连续性。数字档案可在保留原始影像的同时提供局部增强、字符对齐和断片拼合工具。",
    recordStatus: "VERIFIED RECORD · PUBLIC DOMAIN",
  },
] as const;
